In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Customer Purchase.csv')

In [3]:
df.head()

   Customer ID  Age  Gender Education   Review Purchased
0         1021   30  Female    School  Average        No
1         1022   68  Female        UG     Poor        No
2         1023   70  Female        PG     Good        No
3         1024   72  Female        PG     Good        No
4         1025   16  Female        UG  Average        No

In [4]:
df = df.iloc[:, 1:]

In [5]:
df.sample(5)

    Age  Gender Education   Review Purchased
25   57  Female    School     Good        No
49   25  Female        UG     Good        No
21   32    Male        PG  Average        No
30   73    Male        UG  Average        No
48   39  Female        UG     Good       Yes

In [6]:
df = df.iloc[:, 2:]

In [26]:
df.head(10)

  Education   Review Purchased
0    School  Average        No
1        UG     Poor        No
2        PG     Good        No
3        PG     Good        No
4        UG  Average        No
5    School  Average       Yes
6    School     Good        No
7    School     Poor       Yes
8        UG  Average        No
9        UG     Good       Yes

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
X_train.head()

   Education   Review
28    School     Poor
0     School  Average
34    School  Average
29        UG  Average
17        UG     Poor

In [11]:
oe = OrdinalEncoder(categories=[['School', 'UG', 'PG'], ['Poor', 'Average', 'Good']])

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['School', 'UG', 'PG'], ['Poor', 'Average', 'Good']])

In [13]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[0., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [1., 2.],
       [1., 2.],
       [0., 2.]])

In [15]:
oe.categories_

[array(['School', 'UG', 'PG'], dtype=object),
 array(['Poor', 'Average', 'Good'], dtype=object)]

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
le = LabelEncoder()

In [18]:
le.fit(y_train)

LabelEncoder()

In [19]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [20]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [21]:
y_train

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0])